version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - yum install -y maven
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-2 --no-include-email)
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package
      - docker build -t akotau .
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - docker tag akotau:latest 324017272082.dkr.ecr.us-east-2.amazonaws.com/akotau:latest
      - docker push 324017272082.dkr.ecr.us-east-2.amazonaws.com/akotau:latest
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"hello_app","imageUri":"%s"}]' 324017272082.dkr.ecr.us-east-2.amazonaws.com/akotau:latest > imagedefinitions.json

artifacts:
  files:
    - target/aws-code-build.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'